name: Daily User Sync

on:
  schedule:
    - cron: "0 12 * * *" # Executa todos os dias às 12:00 UTC
  workflow_dispatch: # Permite execução manual

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Verificar horário
        run: date

      - name: Instalar o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependências
        run: npm install

      - name: Executar o script fetchContacts.js (gera users.json)
        run: node fetchContacts.js

      - name: Executar o script filterUsers.js (gera activeUsers.json e nonActiveUsers.json)
        run: node filterUsers.js

      - name: Upload dos arquivos JSON gerados
        uses: actions/upload-artifact@v3
        with:
          name: arquivos-filtrados
          path: |
            activeUsers.json
            nonActiveUsers.json

      - name: Verificar conteúdo do arquivo credentials.json
        run: cat credentials.json

      - name: Atualizar Google Sheets
        run: node updateSheets.js

      - name: Listar arquivos no diretório
        run: ls -l
